version: '3.2'

services:
  tombola-back-end:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: tombola-back-end:latest
    container_name: tombola-back-end-container
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: 'host'
